%% run_device_composition_analysis.m
% DEVICE COMPOSITION AND INSTALLED CAPACITY ANALYSIS
%
% Purpose:
%   Lightweight post-processing script to answer the research questions:
%   1. Individually, how many devices are required to make the stressed IEEE 33-bus feeder voltage-feasible?
%   2. In hybrid combinations, how many devices of each type are required?
%   3. What is the installed rating/capacity of each solution, not only the device count?
%   4. Which composition gives the best overall outcome when considering voltage feasibility,
%      Vmin/Vmax, total loss, device count, installed capacity, and practical interpretation?
%
% This script does NOT rerun optimisation and does NOT modify solver results.
% It uses the final reported cases and generates a comprehensive composition analysis
% with installed ratings, loss metrics, and recommendation categories.
%
% Interpretation notes:
%   - STATCOM and ES-1 are compared using installed MVAr because both have explicit reactive-power limits.
%   - Standard ES is reported as controllable non-critical-load capacity, not MVAr injection.
%   - ESS requires inverter MVA and battery MWh normalisation (marked if not available).
%   - PV is reported by installed MW capacity at the reference scale.
%
% Output:
%   04_results/es_framework/tables/table_device_composition_analysis.csv
%   04_results/es_framework/figures/fig_device_composition_feasibility.png
%   04_results/es_framework/figures/fig_device_composition_loss.png
%   04_results/es_framework/figures/fig_device_composition_device_count.png
%   04_results/es_framework/figures/fig_device_composition_installed_capacity.png

clear; clc; close all;

%% Paths
script_dir = fileparts(mfilename('fullpath'));
framework_root = fileparts(script_dir);
repo_root = fileparts(framework_root);

out_tabs = fullfile(repo_root, '04_results', 'es_framework', 'tables');
out_figs = fullfile(repo_root, '04_results', 'es_framework', 'figures');
if ~exist(out_tabs, 'dir'), mkdir(out_tabs); end
if ~exist(out_figs, 'dir'), mkdir(out_figs); end

%% Base assumptions from the existing study
Sbase_MVA = 10.0;
Qs_max_pu = 0.10;           % STATCOM per-device reactive limit
Qes_max_pu = 0.10;          % ES-1 per-device reactive limit

rho = 0.70;                 % Standard ES engagement factor
u_min = 0.20;               % Standard ES minimum utilisation
P_total_peak_pu = 0.4458;   % Peak active load (pu at hour 20)
Q_total_peak_pu = 0.2760;   % Peak reactive load (pu at hour 20)
PV_ref_scale = 2.7;         % Stage 10 PV reference capacity (MW)
PV_max_scale = 2.0;         % Maximum PV scale in tested sweep (multiplier of reference)

% No support case loss and voltage (baseline for comparison)
Loss_baseline_pu = 0.6711;
Vmin_baseline_pu = 0.8308;

% Derived system-level values
P_peak_MW = P_total_peak_pu * Sbase_MVA;
Q_peak_MVAr = Q_total_peak_pu * Sbase_MVA;
S_peak_MVA = sqrt(P_peak_MW^2 + Q_peak_MVAr^2);

ControllableLoadP_MW = rho * P_peak_MW;
ControllableLoadQ_MVAr = rho * Q_peak_MVAr;
ControllableLoadS_MVA = rho * S_peak_MVA;
MaxReducibleP_MW = ControllableLoadP_MW * (1 - u_min);
MaxReducibleQ_MVAr = ControllableLoadQ_MVAr * (1 - u_min);
MaxReducibleS_MVA = ControllableLoadS_MVA * (1 - u_min);

STATCOM_per_device_MVAr = Qs_max_pu * Sbase_MVA;
ES1_per_device_MVAr = Qes_max_pu * Sbase_MVA;

%% Table column arrays
CaseGroup = {};
CaseName = {};
Composition = {};
N_ES = [];
N_STATCOM = [];
N_ESS = [];
N_ES1 = [];
PV_Included = {};
PV_Scale = [];
VoltageFeasible = {};
Vmin_pu = [];
Vmax_pu = [];
TotalLoss_pu = [];
LossReduction_pct = [];
VoltageRecovery_pu = [];
TotalSupportDevices = [];
TotalTraditionalSupport = [];
TotalESBasedDevices = [];
TotalSTATCOM_MVAr = [];
TotalES1Reactive_MVAr = [];
TotalReactiveSupport_MVAr = [];
TotalPVCapacity_MW = [];
ControllableLoadP_MW_col = [];
ControllableLoadQ_MVAr_col = [];
ControllableLoadS_MVA_col = [];
MaxReducibleP_MW_col = [];
MaxReducibleQ_MVAr_col = [];
MaxReducibleS_MVA_col = [];
PerESSInverter_MVA = {};
TotalESSInverter_MVA = {};
PerESSEnergy_MWh = {};
TotalESSEnergy_MWh = {};
MainSupportMechanism = {};
RatingInterpretation = {};
OverallInterpretation = {};
RecommendationCategory = {};
RecommendationNote = {};

%% Case 1: No support (baseline)
addCase('Baseline', 'No support', 'No support', ...
    0, 0, 0, 0, ...
    'No', NaN, ...
    'No', 0.8308, NaN, 0.6711, ...
    0, 0, 0, ...
    0, 0, 0, ...
    'None', ...
    'N/A', 'N/A', ...
    0, NaN, NaN, NaN, NaN, NaN, NaN, ...
    'N/A', 'N/A', 'N/A', 'N/A', ...
    'Reference stressed feeder; severe undervoltage', ...
    'Reference only', ...
    'Baseline case with no voltage support.');

%% Case 2: STATCOM only
addCase('Individual', 'STATCOM only', '7 STATCOM', ...
    0, 7, 0, 0, ...
    'No', NaN, ...
    'Yes', 0.9500, NaN, 0.5365, ...
    7, 0, 7, ...
    7*STATCOM_per_device_MVAr, 0, 7*STATCOM_per_device_MVAr, ...
    'Reactive compensation', ...
    '7 STATCOM x 1.0 MVAr = 7.0 MVAr', '7.0 MVAr', ...
    0, NaN, NaN, NaN, NaN, NaN, NaN, ...
    'N/A', 'N/A', 'N/A', 'N/A', ...
    'Traditional reactive-support benchmark; feasible but high device count', ...
    'Traditional reactive benchmark', ...
    'Reactive injection only; locations selected by MISOCP placement.');

%% Case 3: ESS only
addCase('Individual', 'ESS only', '3 ESS', ...
    0, 0, 3, 0, ...
    'No', NaN, ...
    'Yes', 0.9500, NaN, 0.4337, ...
    3, 0, 3, ...
    0, 0, 0, ...
    'Storage/inverter support', ...
    'Requires ESS inverter and energy rating extraction', 'Requires ESS rating', ...
    0, NaN, NaN, NaN, NaN, NaN, NaN, ...
    'N/A', 'N/A', 'N/A', 'N/A', ...
    'Fewer devices than STATCOM; requires inverter MVA and battery MWh sizing', ...
    'Best traditional standalone by device count', ...
    'ESS should be compared using both inverter power rating and battery energy capacity.');

%% Case 4: Standard ES only
addCase('Individual', 'Standard ES only', '32 standard ES', ...
    32, 0, 0, 0, ...
    'No', NaN, ...
    'No', 0.9324, NaN, 0.1180, ...
    0, 0, 32, ...
    0, 0, 0, ...
    'Non-critical load control', ...
    'Controllable load capacity; no independent reactive injection', 'Load control only', ...
    0, ControllableLoadP_MW, ControllableLoadQ_MVAr, ControllableLoadS_MVA, ...
    MaxReducibleP_MW, MaxReducibleQ_MVAr, MaxReducibleS_MVA, ...
    'N/A', 'N/A', 'N/A', 'N/A', ...
    'Standard ES cannot achieve voltage feasibility alone despite 32 devices', ...
    'Not sufficient alone', ...
    'Standard ES reduces load but has no independent reactive injection.');

%% Case 5: Standard ES + STATCOM
addCase('Hybrid', 'Standard ES + STATCOM', '32 ES + 2 STATCOM', ...
    32, 2, 0, 0, ...
    'No', NaN, ...
    'Yes', 0.9500, NaN, 0.0786, ...
    2, 2, 34, ...
    2*STATCOM_per_device_MVAr, 0, 2*STATCOM_per_device_MVAr, ...
    'Load control plus reactive compensation', ...
    'Hybrid: 32 ES (load control) + 2 STATCOM (1.0 MVAr each)', '2.0 MVAr STATCOM', ...
    0, ControllableLoadP_MW, ControllableLoadQ_MVAr, ControllableLoadS_MVA, ...
    MaxReducibleP_MW, MaxReducibleQ_MVAr, MaxReducibleS_MVA, ...
    'N/A', 'N/A', 'N/A', 'N/A', ...
    'Lowest-loss hybrid feasible case with full ES deployment (32 units + 2 STATCOM)', ...
    'Lowest-loss feasible hybrid', ...
    'Standard ES reduces STATCOM requirement from 7 to 2 but does not eliminate it.');

%% Case 6: Standard ES + ESS
addCase('Hybrid', 'Standard ES + ESS', '32 ES + 1 ESS', ...
    32, 0, 1, 0, ...
    'No', NaN, ...
    'Yes', 0.9544, NaN, 0.0826, ...
    1, 1, 33, ...
    0, 0, 0, ...
    'Load control plus storage/inverter support', ...
    'Hybrid: 32 ES + 1 ESS (inverter and energy rating needed)', 'Requires ESS rating', ...
    0, ControllableLoadP_MW, ControllableLoadQ_MVAr, ControllableLoadS_MVA, ...
    MaxReducibleP_MW, MaxReducibleQ_MVAr, MaxReducibleS_MVA, ...
    'N/A', 'N/A', 'N/A', 'N/A', ...
    'Low-loss hybrid feasible case; standard ES reduces ESS requirement from 3 to 1', ...
    'Low-loss feasible hybrid', ...
    'Standard ES reduces ESS requirement from 3 to 1 but does not eliminate it.');

%% Case 7: Standard ES + STATCOM + ESS joint
addCase('Hybrid', 'Standard ES joint traditional support', '32 ES + 1 ESS', ...
    32, 0, 1, 0, ...
    'No', NaN, ...
    'Yes', 0.9544, NaN, 0.0826, ...
    1, 1, 33, ...
    0, 0, 0, ...
    'Joint load control plus storage', ...
    'Joint opt still requires 1 ESS; standard ES cannot eliminate support floor', 'Requires ESS rating', ...
    0, ControllableLoadP_MW, ControllableLoadQ_MVAr, ControllableLoadS_MVA, ...
    MaxReducibleP_MW, MaxReducibleQ_MVAr, MaxReducibleS_MVA, ...
    'N/A', 'N/A', 'N/A', 'N/A', ...
    'Joint optimisation still requires 1 ESS; standard ES cannot remove support floor', ...
    'Standard ES cannot eliminate final support floor', ...
    'Joint optimisation reveals that standard ES cannot fully replace traditional support.');

%% Case 8: ES-1 only
addCase('Individual', 'ES-1 only', '4 ES-1', ...
    0, 0, 0, 4, ...
    'No', NaN, ...
    'Yes', 0.9500, NaN, 0.3806, ...
    0, 0, 4, ...
    0, 4*ES1_per_device_MVAr, 4*ES1_per_device_MVAr, ...
    'Load control plus independent Q_es', ...
    '4 ES-1 x 1.0 MVAr equivalent = 4.0 MVAr reactive support', '4.0 MVAr equivalent', ...
    0, NaN, NaN, NaN, NaN, NaN, NaN, ...
    'N/A', 'N/A', 'N/A', 'N/A', ...
    'Best ES-based standalone voltage-recovery solution; fully replaces STATCOM/ESS', ...
    'Best ES-based standalone voltage-recovery option', ...
    'ES-1 with independent reactive support removes the need for dedicated STATCOM or ESS.');

%% Case 9: ES-1 joint
addCase('Hybrid', 'ES-1 joint traditional support', '4 ES-1 + 0 STATCOM + 0 ESS', ...
    0, 0, 0, 4, ...
    'No', NaN, ...
    'Yes', 0.9500, NaN, 0.3806, ...
    0, 0, 4, ...
    0, 4*ES1_per_device_MVAr, 4*ES1_per_device_MVAr, ...
    'Independent Q_es support', ...
    '4 ES-1 x 1.0 MVAr equivalent = 4.0 MVAr reactive support', '4.0 MVAr equivalent', ...
    0, NaN, NaN, NaN, NaN, NaN, NaN, ...
    'N/A', 'N/A', 'N/A', 'N/A', ...
    'ES-1 removes the substitution floor; no traditional support is needed', ...
    'Best ES-based traditional-support replacement', ...
    'ES-1 removes the need for dedicated traditional support STATCOM or ESS.');

%% Case 10: PV only
addCase('PV extension', 'PV only', 'PV at buses 18, 22, 25, 33', ...
    0, 0, 0, 0, ...
    'Yes', 1.0, ...
    'No', 0.8308, 1.0217, 0.5878, ...
    0, 0, 0, ...
    0, 0, 0, ...
    'Active PV generation only', ...
    'PV at scale 1.0 = 2.7 MW (Stage 10 reference)', '2.7 MW', ...
    2.7, NaN, NaN, NaN, NaN, NaN, NaN, ...
    'N/A', 'N/A', 'N/A', 'N/A', ...
    'PV reduces losses but does not solve undervoltage in the current stressed profile', ...
    'Not sufficient alone under current stressed profile', ...
    'PV generation helps with losses but does not provide sufficient voltage support.');

%% Case 11: PV + ES-1
addCase('PV extension', 'PV + ES-1', 'PV + 8 ES-1', ...
    0, 0, 0, 8, ...
    'Yes', PV_max_scale, ...
    'Yes', 0.9500, 1.0445, 0.4476, ...
    0, 0, 8, ...
    0, 8*ES1_per_device_MVAr, 8*ES1_per_device_MVAr, ...
    'PV plus independent Q_es support', ...
    'PV at scale 2.0 (5.4 MW) + 8 ES-1 x 1.0 MVAr = 8.0 MVAr', '5.4 MW PV + 8.0 MVAr ES-1', ...
    5.4, NaN, NaN, NaN, NaN, NaN, NaN, ...
    'N/A', 'N/A', 'N/A', 'N/A', ...
    'Maintains voltage feasibility up to 200 percent PV scale in the tested Stage 10 sweep', ...
    'Best PV-integrated feasible case in tested Stage 10 setup', ...
    'ES-1 integration with PV maintains voltage feasibility across high penetration scenarios.');

%% Compute derived metrics and build table
nCases = length(CaseName);
T_data = cell(nCases, 1);

for i = 1:nCases
    % Calculate derived metrics
    LossReduction_pct(i) = (Loss_baseline_pu - TotalLoss_pu(i)) / Loss_baseline_pu * 100;
    VoltageRecovery_pu(i) = Vmin_pu(i) - Vmin_baseline_pu;
    TotalSupportDevices(i) = N_ES(i) + N_STATCOM(i) + N_ESS(i) + N_ES1(i);
    TotalTraditionalSupport(i) = N_STATCOM(i) + N_ESS(i);
    TotalESBasedDevices(i) = N_ES(i) + N_ES1(i);
end

T = table(CaseGroup', CaseName', Composition', ...
    N_ES', N_STATCOM', N_ESS', N_ES1', ...
    PV_Included', PV_Scale', ...
    VoltageFeasible', Vmin_pu', Vmax_pu', TotalLoss_pu', ...
    LossReduction_pct', VoltageRecovery_pu', ...
    TotalSupportDevices', TotalTraditionalSupport', TotalESBasedDevices', ...
    TotalSTATCOM_MVAr', TotalES1Reactive_MVAr', TotalReactiveSupport_MVAr', ...
    TotalPVCapacity_MW', ...
    ControllableLoadP_MW_col', ControllableLoadQ_MVAr_col', ControllableLoadS_MVA_col', ...
    MaxReducibleP_MW_col', MaxReducibleQ_MVAr_col', MaxReducibleS_MVA_col', ...
    PerESSInverter_MVA', TotalESSInverter_MVA', ...
    PerESSEnergy_MWh', TotalESSEnergy_MWh', ...
    MainSupportMechanism', RatingInterpretation', ...
    OverallInterpretation', RecommendationCategory', RecommendationNote', ...
    'VariableNames', {'CaseGroup','CaseName','Composition', ...
    'N_ES','N_STATCOM','N_ESS','N_ES1', ...
    'PV_Included','PV_Scale', ...
    'VoltageFeasible','Vmin_pu','Vmax_pu','TotalLoss_pu', ...
    'LossReduction_pct','VoltageRecovery_pu', ...
    'TotalSupportDevices','TotalTraditionalSupport','TotalESBasedDevices', ...
    'TotalSTATCOM_MVAr','TotalES1Reactive_MVAr','TotalReactiveSupport_MVAr', ...
    'TotalPVCapacity_MW', ...
    'ControllableLoadP_MW','ControllableLoadQ_MVAr','ControllableLoadS_MVA', ...
    'MaxReducibleP_MW','MaxReducibleQ_MVAr','MaxReducibleS_MVA', ...
    'PerESSInverter_MVA','TotalESSInverter_MVA', ...
    'PerESSEnergy_MWh','TotalESSEnergy_MWh', ...
    'MainSupportMechanism','RatingInterpretation', ...
    'OverallInterpretation','RecommendationCategory','RecommendationNote'});

out_csv = fullfile(out_tabs, 'table_device_composition_analysis.csv');
writetable(T, out_csv);

%% Figure 1: Voltage Feasibility (Vmin_pu with feasibility line)
fig1 = figure('Color','w','Position',[100 100 1200 500]);
x_pos = 1:nCases;
colors = repmat([0.3 0.5 0.8], nCases, 1);
for i = 1:nCases
    if strcmp(VoltageFeasible{i}, 'Yes')
        colors(i, :) = [0.2 0.7 0.2];  % Green for feasible
    else
        colors(i, :) = [0.8 0.2 0.2];  % Red for infeasible
    end
end

bar_h = bar(x_pos, Vmin_pu, 0.6);
hold on;

% Color bars individually
for i = 1:nCases
    bar_h.CData(i,:) = colors(i,:);
end

yline(0.95, 'k--', 'LineWidth', 2, 'Label', 'Feasibility threshold (0.95 pu)');
yline(Vmin_baseline_pu, 'r:', 'LineWidth', 2, 'Label', 'Baseline (0.8308 pu)');

xlabel('Case', 'FontSize', 11, 'FontWeight', 'bold');
ylabel('Minimum voltage (pu)', 'FontSize', 11, 'FontWeight', 'bold');
title('Voltage Feasibility Across Individual and Hybrid Compositions', 'FontSize', 12, 'FontWeight', 'bold');
set(gca, 'XTick', x_pos, 'XTickLabel', CaseName, 'XTickLabelRotation', 45);
grid on; grid minor;
ylim([0.80 1.00]);
legend('Location', 'best');
hold off;

out_fig1 = fullfile(out_figs, 'fig_device_composition_feasibility.png');
try
    exportgraphics(fig1, out_fig1, 'Resolution', 300);
catch
    saveas(fig1, out_fig1);
end
close(fig1);

%% Figure 2: Total Loss
fig2 = figure('Color','w','Position',[100 100 1200 500]);
colors2 = repmat([0.5 0.5 0.5], nCases, 1);
for i = 1:nCases
    if strcmp(VoltageFeasible{i}, 'Yes')
        colors2(i, :) = [0.2 0.7 0.2];  % Green for feasible
    else
        colors2(i, :) = [0.8 0.2 0.2];  % Red for infeasible
    end
end

bar_h2 = bar(x_pos, TotalLoss_pu, 0.6);
for i = 1:nCases
    bar_h2.CData(i,:) = colors2(i,:);
end

yline(Loss_baseline_pu, 'r:', 'LineWidth', 2, 'Label', 'Baseline (0.6711 pu)');
xlabel('Case', 'FontSize', 11, 'FontWeight', 'bold');
ylabel('Total loss (pu)', 'FontSize', 11, 'FontWeight', 'bold');
title('Total Loss Across Device Compositions', 'FontSize', 12, 'FontWeight', 'bold');
set(gca, 'XTick', x_pos, 'XTickLabel', CaseName, 'XTickLabelRotation', 45);
grid on; grid minor;
legend('Location', 'best');

% Annotate infeasible cases
for i = 1:nCases
    if strcmp(VoltageFeasible{i}, 'No')
        text(i, TotalLoss_pu(i) + 0.02, 'Infeasible', ...
            'HorizontalAlignment','center', 'FontSize', 9, 'FontWeight', 'bold', 'Color', [0.8 0.2 0.2]);
    end
end

out_fig2 = fullfile(out_figs, 'fig_device_composition_loss.png');
try
    exportgraphics(fig2, out_fig2, 'Resolution', 300);
catch
    saveas(fig2, out_fig2);
end
close(fig2);

%% Figure 3: Device Count (stacked bar chart)
fig3 = figure('Color','w','Position',[100 100 1200 550]);

% Prepare data for stacked bar: [N_ES, N_STATCOM, N_ESS, N_ES1]
device_counts = [N_ES', N_STATCOM', N_ESS', N_ES1'];

bar_h3 = bar(x_pos, device_counts, 'stacked', 'FaceColor', 'flat');
bar_h3(1).CData = repmat([0.8 0.5 0.2], nCases, 1);  % ES: brown
bar_h3(2).CData = repmat([0.2 0.5 0.8], nCases, 1);  % STATCOM: blue
bar_h3(3).CData = repmat([0.8 0.2 0.2], nCases, 1);  % ESS: red
bar_h3(4).CData = repmat([0.2 0.8 0.2], nCases, 1);  % ES-1: green

xlabel('Case', 'FontSize', 11, 'FontWeight', 'bold');
ylabel('Device count', 'FontSize', 11, 'FontWeight', 'bold');
title('Device Count Composition Across Planning Options', 'FontSize', 12, 'FontWeight', 'bold');
set(gca, 'XTick', x_pos, 'XTickLabel', CaseName, 'XTickLabelRotation', 45);
legend('Standard ES', 'STATCOM', 'ESS', 'ES-1', 'Location', 'best', 'Fontsize', 10);
grid on; grid minor;

out_fig3 = fullfile(out_figs, 'fig_device_composition_device_count.png');
try
    exportgraphics(fig3, out_fig3, 'Resolution', 300);
catch
    saveas(fig3, out_fig3);
end
close(fig3);

%% Figure 4: Installed Capacity
% This figure shows multiple capacity types side by side or grouped
fig4 = figure('Color','w','Position',[100 100 1400 600]);

% Prepare grouped data: STATCOM MVAr, ES-1 MVAr, PV MW, ES load control MVA
capacity_data = [TotalSTATCOM_MVAr', TotalES1Reactive_MVAr', TotalPVCapacity_MW', ControllableLoadS_MVA_col'];

% Create grouped bar chart (mask out NaN for plotting)
capacity_display = capacity_data;
capacity_display(isnan(capacity_display)) = 0;

bar_h4 = bar(x_pos, capacity_display, 'grouped');
bar_h4(1).CData = repmat([0.2 0.5 0.8], nCases, 1);   % STATCOM: blue
bar_h4(2).CData = repmat([0.2 0.8 0.2], nCases, 1);   % ES-1: green
bar_h4(3).CData = repmat([1.0 0.8 0.2], nCases, 1);   % PV: orange
bar_h4(4).CData = repmat([0.8 0.5 0.2], nCases, 1);   % ES load: brown

xlabel('Case', 'FontSize', 11, 'FontWeight', 'bold');
ylabel('Installed Capacity (MVA / MVAr / MW)', 'FontSize', 11, 'FontWeight', 'bold');
title('Installed Capacity Across Device Compositions', 'FontSize', 12, 'FontWeight', 'bold');
set(gca, 'XTick', x_pos, 'XTickLabel', CaseName, 'XTickLabelRotation', 45);
legend('STATCOM (MVAr)', 'ES-1 Reactive (MVAr)', 'PV (MW)', 'ES Controllable Load (MVA)', 'Location', 'best', 'FontSize', 10);
grid on; grid minor;

note_text = {'Note: STATCOM and ES-1 in MVAr; PV in MW; ES in MVA (controllable load).', ...
             'ESS inverter/energy marked as requiring normalisation if not extracted.'};
text(0.02, 0.02, sprintf('%s\\n%s', note_text{1}, note_text{2}), 'Units', 'normalized', ...
    'FontSize', 8, 'VerticalAlignment', 'bottom', 'Interpreter', 'none');

out_fig4 = fullfile(out_figs, 'fig_device_composition_installed_capacity.png');
try
    exportgraphics(fig4, out_fig4, 'Resolution', 300);
catch
    saveas(fig4, out_fig4);
end
close(fig4);

%% Command window summary
fprintf('\n============================================================\n');
fprintf(' DEVICE COMPOSITION AND INSTALLED CAPACITY ANALYSIS COMPLETE\n');
fprintf('============================================================\n');
fprintf('\n Study System Base: %.1f MVA\n', Sbase_MVA);
fprintf(' Baseline Case (No support):\n');
fprintf('   Vmin = %.4f pu, Loss = %.4f pu\n\n', Vmin_baseline_pu, Loss_baseline_pu);

fprintf(' Individual Technology Results:\n');
fprintf('   STATCOM-only:  7 devices x %.2f pu = %.1f MVAr total, Feasible\n', ...
    Qs_max_pu, 7*STATCOM_per_device_MVAr);
fprintf('   ESS-only:      3 devices, Feasible (requires inverter MVA and energy MWh normalisation)\n');
fprintf('   Standard ES:   32 devices, INFEASIBLE (no independent reactive support)\n');
fprintf('   ES-1 only:     4 devices x %.2f pu = %.1f MVAr equivalent, Feasible\n\n', ...
    Qes_max_pu, 4*ES1_per_device_MVAr);

fprintf(' Hybrid Technology Results:\n');
fprintf('   Standard ES + STATCOM: 32 ES + 2 STATCOM (2.0 MVAr), Feasible, LOWEST LOSS (0.0786 pu)\n');
fprintf('   Standard ES + ESS:     32 ES + 1 ESS, Feasible, LOW LOSS (0.0826 pu)\n');
fprintf('   Standard ES cannot eliminate final support floor; always requires traditional support\n\n');

fprintf(' ES-1 as Traditional Support Replacement:\n');
fprintf('   ES-1 only:     4 devices x %.2f pu = %.1f MVAr equivalent, Feasible\n', ...
    Qes_max_pu, 4*ES1_per_device_MVAr);
fprintf('   ES-1 removes the need for dedicated STATCOM or ESS\n');
fprintf('   ES-1 is the strongest ES-based standalone voltage-recovery option\n\n');

fprintf(' PV Integration Results:\n');
fprintf('   PV-only:       INFEASIBLE (reduces loss but no voltage support)\n');
fprintf('   PV + ES-1:     8 devices x %.2f pu = %.1f MVAr equivalent, Feasible at 200%% PV scale\n\n', ...
    Qes_max_pu, 8*ES1_per_device_MVAr);

fprintf(' Key Findings:\n');
fprintf('   1. STATCOM, ESS, and ES-1 individually restore voltage; standard ES and PV do not\n');
fprintf('   2. Standard ES hybrids achieve lowest losses but require 32 ES devices + traditional support\n');
fprintf('   3. ES-1 fully replaces traditional support: 4 ES-1 vs 7 STATCOM or 3 ESS\n');
fprintf('   4. PV benefits from ES-1 integration; standalone PV is insufficient under stress\n');
fprintf('   5. Recommendation categories:\n');
fprintf('      - Best standalone (ES-based):    ES-1 only (4 devices, 4.0 MVAr)\n');
fprintf('      - Lowest-loss feasible hybrid:   Standard ES + STATCOM (32 ES + 2 STATCOM, 0.0786 pu loss)\n');
fprintf('      - Best traditional standalone:   ESS-only (3 devices)\n');
fprintf('      - Best PV-integrated:            PV + ES-1 at 200%% PV scale\n\n');

fprintf(' Output Files:\n');
fprintf('   Saved table:      %s\n', out_csv);
fprintf('   Figure 1 (Feasibility): %s\n', fullfile(out_figs, 'fig_device_composition_feasibility.png'));
fprintf('   Figure 2 (Loss):        %s\n', fullfile(out_figs, 'fig_device_composition_loss.png'));
fprintf('   Figure 3 (Device Count):%s\n', fullfile(out_figs, 'fig_device_composition_device_count.png'));
fprintf('   Figure 4 (Capacity):    %s\n\n', fullfile(out_figs, 'fig_device_composition_installed_capacity.png'));
fprintf('============================================================\n\n');

%% Local helper: addCase
function addCase(caseGroup, caseName, composition, ...
    n_es, n_statcom, n_ess, n_es1, ...
    pv_included, pv_scale, ...
    voltage_feasible, vmin_pu, vmax_pu, total_loss_pu, ...
    total_traditional_support, total_es_based, total_support_devices, ...
    total_statcom_mvar, total_es1_reactive_mvar, total_reactive_support_mvar, ...
    main_support_mechanism, ...
    rating_interpretation, rating_text, ...
    total_pv_capacity_mw, ...
    controllable_load_p, controllable_load_q, controllable_load_s, ...
    max_reducible_p, max_reducible_q, max_reducible_s, ...
    per_ess_inverter_mva, total_ess_inverter_mva, ...
    per_ess_energy_mwh, total_ess_energy_mwh, ...
    overall_interpretation, recommendation_category, recommendation_note)

    assignin('caller', 'CaseGroup', [evalin('caller','CaseGroup'), {caseGroup}]);
    assignin('caller', 'CaseName', [evalin('caller','CaseName'), {caseName}]);
    assignin('caller', 'Composition', [evalin('caller','Composition'), {composition}]);

    assignin('caller', 'N_ES', [evalin('caller','N_ES'), n_es]);
    assignin('caller', 'N_STATCOM', [evalin('caller','N_STATCOM'), n_statcom]);
    assignin('caller', 'N_ESS', [evalin('caller','N_ESS'), n_ess]);
    assignin('caller', 'N_ES1', [evalin('caller','N_ES1'), n_es1]);

    assignin('caller', 'PV_Included', [evalin('caller','PV_Included'), {pv_included}]);
    assignin('caller', 'PV_Scale', [evalin('caller','PV_Scale'), pv_scale]);

    assignin('caller', 'VoltageFeasible', [evalin('caller','VoltageFeasible'), {voltage_feasible}]);
    assignin('caller', 'Vmin_pu', [evalin('caller','Vmin_pu'), vmin_pu]);
    assignin('caller', 'Vmax_pu', [evalin('caller','Vmax_pu'), vmax_pu]);
    assignin('caller', 'TotalLoss_pu', [evalin('caller','TotalLoss_pu'), total_loss_pu]);

    assignin('caller', 'TotalTraditionalSupport', [evalin('caller','TotalTraditionalSupport'), total_traditional_support]);
    assignin('caller', 'TotalESBasedDevices', [evalin('caller','TotalESBasedDevices'), total_es_based]);
    assignin('caller', 'TotalSupportDevices', [evalin('caller','TotalSupportDevices'), total_support_devices]);

    assignin('caller', 'TotalSTATCOM_MVAr', [evalin('caller','TotalSTATCOM_MVAr'), total_statcom_mvar]);
    assignin('caller', 'TotalES1Reactive_MVAr', [evalin('caller','TotalES1Reactive_MVAr'), total_es1_reactive_mvar]);
    assignin('caller', 'TotalReactiveSupport_MVAr', [evalin('caller','TotalReactiveSupport_MVAr'), total_reactive_support_mvar]);

    assignin('caller', 'MainSupportMechanism', [evalin('caller','MainSupportMechanism'), {main_support_mechanism}]);
    assignin('caller', 'RatingInterpretation', [evalin('caller','RatingInterpretation'), {rating_interpretation}]);

    assignin('caller', 'TotalPVCapacity_MW', [evalin('caller','TotalPVCapacity_MW'), total_pv_capacity_mw]);

    assignin('caller', 'ControllableLoadP_MW_col', [evalin('caller','ControllableLoadP_MW_col'), controllable_load_p]);
    assignin('caller', 'ControllableLoadQ_MVAr_col', [evalin('caller','ControllableLoadQ_MVAr_col'), controllable_load_q]);
    assignin('caller', 'ControllableLoadS_MVA_col', [evalin('caller','ControllableLoadS_MVA_col'), controllable_load_s]);

    assignin('caller', 'MaxReducibleP_MW_col', [evalin('caller','MaxReducibleP_MW_col'), max_reducible_p]);
    assignin('caller', 'MaxReducibleQ_MVAr_col', [evalin('caller','MaxReducibleQ_MVAr_col'), max_reducible_q]);
    assignin('caller', 'MaxReducibleS_MVA_col', [evalin('caller','MaxReducibleS_MVA_col'), max_reducible_s]);

    assignin('caller', 'PerESSInverter_MVA', [evalin('caller','PerESSInverter_MVA'), {per_ess_inverter_mva}]);
    assignin('caller', 'TotalESSInverter_MVA', [evalin('caller','TotalESSInverter_MVA'), {total_ess_inverter_mva}]);
    assignin('caller', 'PerESSEnergy_MWh', [evalin('caller','PerESSEnergy_MWh'), {per_ess_energy_mwh}]);
    assignin('caller', 'TotalESSEnergy_MWh', [evalin('caller','TotalESSEnergy_MWh'), {total_ess_energy_mwh}]);

    assignin('caller', 'OverallInterpretation', [evalin('caller','OverallInterpretation'), {overall_interpretation}]);
    assignin('caller', 'RecommendationCategory', [evalin('caller','RecommendationCategory'), {recommendation_category}]);
    assignin('caller', 'RecommendationNote', [evalin('caller','RecommendationNote'), {recommendation_note}]);
end
